# Generated by Django 3.1.2 on 2020-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('shape', models.IntegerField(choices=[(1, 'Rectangle'), (2, 'Oval')], default=1)),
                ('coordinateX', models.IntegerField()),
                ('coordinateY', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('tables', models.ManyToManyField(to='reservation.Table')),
            ],
        ),
    ]
